name: "Trivy"
author: "Cloudfy9 <contact@cloudfy9.com>"
description: "GitHub action to scan docker images for vulnerability issues using trivy."
inputs:
  image_name:
    description: "This input contains the docker images to scan"
    required: true
  version:
    description: "This input contains the trivy version"
    required: false
    default: "0.23.0"
  format:
    description: "This input contains the scan output format e.g. table or json"
    required: false
    default: "table"
  severity:
    description: "This input contains the comma separated list of severities e.g. UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
    required: false
    default: "HIGH,CRITICAL"
  additional_options:
    description: "This input contains the additional optional parameters e.g. --exit-code 128 --vuln-type os,library"
    required: false
    default: "--exit-code 128 --vuln-type os,library"
branding:
  icon: "camera"
  color: "red"
runs:
  using: "composite"
  steps:
    - name: Run Trivy Scan
      shell: bash
      run: ${{ github.action_path }}/trivy.sh
      env:
        INPUT_IMAGE_NAME: ${{ inputs.image_name }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_SEVERITY: ${{ inputs.severity }}
        INPUT_ADDITIONAL_OPTIONS: ${{ inputs.additional_options }}
        ACTION_PATH: ${{ github.action_path }}
