name: "Trivy"
author: "Cloudfy9 <contact@cloudfy9.com>"
description: "GitHub action to scan docker images for vulnerability issues using trivy."
inputs:
  images:
    description: "This input contains the docker images to scan"
    required: true
  version:
    description: "This input contains the trivy version"
    required: false
    default: "0.1.6"
branding:
  icon: "camera"
  color: "red"
runs:
  using: "composite"
  steps:
    - name: Run Trivy Scan
      shell: bash
      run: ${{ github.action_path }}/trivy.sh
      env:
        INPUT_IMAGES: ${{ inputs.images }}
        ACTION_PATH: ${{ github.action_path }}
